create database Inventory_Service;
use Inventory_Service;

CREATE TABLE INVENTORY_DETAILS
 (
        ITEM_ID INTEGER NOT NULL AUTO_INCREMENT,
        ITEM_CODE VARCHAR(200) NOT NULL,
        ITEM_CATEGORY VARCHAR(200) NOT NULL,        
        ITEM_QUANTITY INTEGER  NOT NULL,
        ITEM_PRICE DOUBLE NOT NULL,
		CONSTRAINT Item_Inventory_PK PRIMARY KEY(ITEM_ID)
);

CREATE TABLE INVENTORY_TRANSACTION
 (
        TRANSACTION_ID INTEGER NOT NULL,
        ITEM_ID INTEGER NOT NULL,
        CUSTOMER_ID VARCHAR(200) NOT NULL,
        CUSTOMER_EMAIL VARCHAR(200) NOT NULL,
        TRANSACTION_TYPE VARCHAR(10) NOT NULL,
        TRANSACTION_QUANTITY INTEGER  NOT NULL,
        TRANSACTION_DATE DATE,
		CONSTRAINT ITEM_TRANSACTION_PK PRIMARY KEY(TRANSACTION_ID),
		CONSTRAINT ITEM_TRANSACTION_FK FOREIGN KEY(ITEM_ID) REFERENCES INVENTORY_DETAILS(ITEM_ID)
);