server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: apiGateway
  boot:
    admin:
      client:
        url: http://localhost:8085
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables automatic service discovery
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - LoggingFilter
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory-service/**
          filters:
            - LoggingFilter
  spring:
    security:
      user:
        name: admin
        password: admin


